export interface User {
  id: string
  username: string
  name: string
}

export interface AuthState {
  token: string | null
  user: User | null
}

// WP REST API shapes

export interface WPPost {
  id: number
  title: { rendered: string }
  slug: string
  link: string
  status?: string
  acf: {
    content: WPAcfElement[]
    favicon?: number
    logo?: number
  }
}

export interface WPAcfElement {
  acf_fc_layout: "element"
  type: "nosubs" | "subs"
  show_in_menu: boolean
  show_content_editor: boolean
  content_title: string
  content_main: string
  content_sub: WPAcfSubElement[] | null
}

export interface WPAcfSubElement {
  content_subtitle: string
  subcontent: string
}

export interface WPMedia {
  id: number
  source_url: string
}

export interface Destination {
  tabId: number
  elementIndex: number
  targetField: "content_main" | "subcontent"
  subIndex?: number
  sectionTitle?: string
  subSectionTitle?: string
}

// Annotation canvas types

export type AnnotationTool = "arrow" | "text" | "line" | "rectangle"

export type AnnotationColor =
  | "#EF4444"
  | "#F59E0B"
  | "#22C55E"
  | "#3B82F6"
  | "#000000"

export interface Annotation {
  id: string
  tool: AnnotationTool
  color: AnnotationColor
  points: number[]
  text?: string
  strokeWidth: number
}

export interface CaptureFlow {
  destination: Destination
  flowType?: "screenshot" | "video"
  cropBounds?: { x: number; y: number; width: number; height: number }
  rawDataUrl?: string
  annotatedDataUrl?: string
  annotations?: Annotation[]
  transcript?: string
  generatedHtml?: string
  videoFileUri?: string
  videoMimeType?: string
  videoWpUrl?: string
  aiError?: string
}

export interface AiSubmitPayload {
  imageDataUrl?: string
  transcript?: string
  context: string
  videoFileUri?: string
  videoBase64?: string
  videoMimeType?: string
}

export interface AiResult {
  contentHtml: string
}

export type EditorScreen =
  | "post-selector"
  | "tab-editor"
  | "annotator"
  | "audio-recorder"
  | "video-recorder"
  | "ai-processing"
  | "content-review"

export interface ResizeWindowMessage {
  type: "RESIZE_WINDOW"
  width: number
}

// Jack QA automation domain types

export type TargetFramework = "playwright" | "cypress"

export type TargetLanguage = "typescript" | "javascript" | "dotnet" | "java"

export interface RecordedAction {
  type: "click" | "input" | "navigate"
  selector: string
  value?: string
  /**
   * The URL navigated to when the type is `navigate`.  This is used to
   * assert correct redirection flows.
   */
  url?: string
  /**
   * A high resolution timestamp (Date.now()) that captures when the
   * action happened.  Useful for ordering and debugging.
   */
  timestamp: number
}

/**
 * A short natural language idea describing a potential test case.  The
 * text is editable by the user and may be regenerated through the AI
 * pipeline.
 */
export interface TestCaseIdea {
  id: string
  text: string
}

/**
 * Representation of a file generated by the AI pipeline.  Each file
 * contains a path (relative to the project root) and its source code.
 */
export interface GeneratedFile {
  /** Relative path, e.g. `pages/Login.page.ts` or `.cursorrules`. */
  path: string
  /** Raw contents of the file. */
  content: string
}

/**
 * Providers and models selected in the settings screen.  The extension
 * supports different AI vendors for media analysis and code generation.
 */
export interface SelectedModels {
  /** Provider used for media analysis (step 0.5). */
  mediaAnalysisProvider: "openai" | "gemini" | "openrouter"
  /** Name of the specific model for media analysis (e.g. "gpt‑4o‑mini"). */
  mediaAnalysisModel: string
  /** Provider used for code generation (step 1). */
  codeGenProvider: "openai" | "gemini" | "groq" | "openrouter" | "grok"
  /** Name of the specific model for code generation. */
  codeGenModel: string
  /** Optional review provider for code review.  If undefined the
   * review feature is disabled. */
  reviewProvider?: string
  /** Name of the review model.  Only used when reviewProvider is set. */
  reviewModel?: string
}

/**
 * Session state maintained during the user's interaction with the
 * extension.  Most of this information lives in the `chrome.storage.session`
 * namespace so that it survives page reloads within the session but
 * disappears once the browser is closed.  Keys and settings live in
 * `chrome.storage.local` via other store helpers.
 */
export interface CapturedScreenshot {
  id: string
  createdAt: number
}

export interface JackSessionState {
  /** All screenshots captured for this site/tab session. */
  screenshots: CapturedScreenshot[]
  /** Base64 data URL of the latest annotated screenshot (for AI). */
  screenshotDataUrl?: string
  /** Legacy inline video; prefer IndexedDB via hasVideo. */
  videoDataUrl?: string
  /** Whether a tab recording is saved for this site session. */
  hasVideo?: boolean
  videoMimeType?: string
  /** Textual description of the captured media after media analysis. */
  mediaDescription?: string
  /** The outerHTML of the element selected by the inspector. */
  htmlContext?: string
  /** CSS selector for the selected element. */
  targetSelector?: string
  /** Sequence of recorded user actions from the recorder. */
  recordedActions: RecordedAction[]
  /** User provided prompt for contextualising the request. */
  customPrompt?: string
  /** Current list of test case ideas. */
  testIdeas: TestCaseIdea[]
  /** Generated code files returned from the AI. */
  generatedFiles: GeneratedFile[]
}

/**
 * Persisted provider keys and model selections.  These settings are
 * stored in `chrome.storage.local` so that the user does not need to
 * reenter them every time.  Each provider can have its own API key and
 * default model.  When a provider is not configured the key is `null`.
 */
// Jack QA background generation status — written by background.ts, read by popup + screens
export type JackGenPhase =
  | "idle"
  | "analyzing-media"
  | "generating-ideas"
  | "generating-code"
  | "error"

export interface JackGenStatus {
  phase: JackGenPhase
  sessionKey?: string
  error?: string
  failedPhase?: "ideas" | "code"
}

export interface ProviderKeys {
  openaiKey: string | null
  geminiKey: string | null
  groqKey: string | null
  openrouterKey: string | null
  grokKey: string | null
  /**
   * Additional model fields can be stored here.  We store the default model
   * names separately to simplify the settings form.
   */
  openaiModel: string | null
  geminiModel: string | null
  groqModel: string | null
  openrouterModel: string | null
  grokModel: string | null
}